import exceptions 
class DataJointError(exceptions.StandardError):
    pass